export const FOOD_TYPES = {
	ADD_FOOD: 'ADD_FOOD',
	REMOVE_FOOD: 'REMOVE_FOOD',
	REMOVE_ONE: 'REMOVE_ONE',
	PLUS_ONE: 'PLUS_ONE',
	MINUS_ONE: 'MINUS_ONE',
	CART_PLUS: 'CART_PLUS',
	SIZE_CHANGE: 'SIZE_CHANGE'
};
