import Foto from '../../assets/pizza.png';

export const meals = [
	{
		id: 0,
		name: 'Pizza Margarita',
		ingredients: [ 'sos', 'ser 2x' ],
		price: 10,
		low_price: 10,
		big_price: 17,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 1,
		name: 'Pizza Napoli',
		ingredients: [ 'sos', 'ser', 'pieczarki' ],
		price: 10,
		low_price: 10,
		big_price: 16,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 2,
		name: 'Pizza Cebulowa',
		ingredients: [ 'sos', 'ser', 'cebula' ],
		price: 10,
		low_price: 10,
		big_price: 16,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 3,
		name: 'Pizza Idea',
		ingredients: [ 'sos', 'ser', 'pieczarki', 'szynka', 'cebula' ],
		price: 11,
		low_price: 11,
		big_price: 18,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 4,
		name: 'Pizza Roco-co',
		ingredients: [ 'sos', 'ser', 'peperoni', 'szynka', 'papryka' ],
		price: 11,
		low_price: 11,
		big_price: 19,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 5,
		name: 'Pizza Hawajska',
		ingredients: [ 'sos', 'ser', 'szynka', 'ananas' ],
		price: 11,
		low_price: 11,
		big_price: 19,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 6,
		name: 'Pizza Raj',
		ingredients: [ 'sos', 'ser', 'pieczarki', 'szynka', 'peperoni', 'kurczak' ],
		price: 11,
		low_price: 11,
		big_price: 20,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 7,
		name: 'Pizza Finezja',
		ingredients: [ 'sos', 'ser', 'kurczak', 'kukurydza', 'ananas' ],
		price: 11,
		low_price: 11,
		big_price: 20,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 8,
		name: 'Pizza Tago',
		ingredients: [ 'sos', 'ser', 'peperoni', 'pieczarki', 'kurczak' ],
		price: 11,
		low_price: 11,
		big_price: 20,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 9,
		name: 'Pizza Picasso',
		ingredients: [ 'sos', 'ser', 'kurczak', 'pomidor', 'oliwki zielone i czarne', 'peperoni' ],
		price: 12,
		low_price: 12,
		big_price: 21,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 10,
		name: 'Pizza Salami',
		ingredients: [ 'sos', 'ser', 'salami', 'pieczarki', 'cebula' ],
		price: 11,
		low_price: 11,
		big_price: 20,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 11,
		name: 'Pizza Jazz',
		ingredients: [ 'sos', 'ser', 'salami', 'cebula', 'peperoni' ],
		price: 11,
		low_price: 11,
		big_price: 20,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 12,
		name: 'Pizza Wegetariańska',
		ingredients: [ 'sos', 'ser', 'pieczarki', 'kukurydza', 'papryka', 'pomidor', 'ogórek' ],
		price: 11,
		low_price: 11,
		big_price: 20,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 13,
		name: 'Pizza Tino',
		ingredients: [ 'sos', 'ser', 'boczek', 'papryka' ],
		price: 12,
		low_price: 12,
		big_price: 21,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 14,
		name: 'Pizza Zzumo',
		ingredients: [ 'sos', 'ser', 'mięso mielone', 'pieczarki' ],
		price: 12,
		low_price: 12,
		big_price: 21,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 15,
		name: 'Pizza Mozarella',
		ingredients: [ 'sos', 'ser', 'ser camembert', 'ser lazur', 'zioła' ],
		price: 12,
		low_price: 12,
		big_price: 21,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 16,
		name: 'Pizza Zora',
		ingredients: [ 'sos', 'ser', 'pieczarki', 'salami/kurczak', 'cebula' ],
		price: 11,
		low_price: 11,
		big_price: 20,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 17,
		name: 'Pizza Variette',
		ingredients: [ 'sos', 'ser', 'szynka', 'cebula/groszek', 'jajko/kurczak', 'kukurydza' ],
		price: 12,
		low_price: 12,
		big_price: 21,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 18,
		name: 'Pizza Neptun',
		ingredients: [ 'sos', 'ser', 'tuńczyk', 'papryka', 'cebula' ],
		price: 12,
		low_price: 12,
		big_price: 21,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 19,
		name: 'Pizza Calzone (pieróg)',
		ingredients: [ 'sos', 'ser', 'pieczarki', 'szynka' ],
		price: 18,
		low_price: 12,
		big_price: 18,
		sizes: [ 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 20,
		name: 'Pizza Gyros',
		ingredients: [ 'sos', 'ser', 'mięso gyros', 'pieczarki' ],
		price: 12,
		low_price: 12,
		big_price: 20,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 21,
		name: 'Pizza Feta',
		ingredients: [ 'sos', 'ser', 'pomidor', 'ser typu Feta', 'oliwki' ],
		price: 11,
		low_price: 11,
		big_price: 20,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 22,
		name: 'Pizza Polonez',
		ingredients: [ 'sos', 'ser', 'brokuły', 'jajka', 'kurczak' ],
		price: 12,
		low_price: 12,
		big_price: 21,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 23,
		name: 'Pizza Firmowa',
		ingredients: [ 'sos', 'ser', 'szynka', 'salami', 'chili', 'pieczarki', 'rukola', 'śmietana' ],
		price: 12,
		low_price: 12,
		big_price: 21,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 24,
		name: 'Pizza Quiz',
		ingredients: [ 'sos', 'ser', '4 składniki do wyboru!' ],
		price: 13,
		low_price: 13,
		big_price: 22,
		sizes: [ 20, 30 ],
		image: Foto,
		number: 1
	},
	{
		id: 25,
		name: 'Pizza Rogata XXL',
		ingredients: [ 'sos', 'ser', '4 składniki do wyboru!' ],
		price: 35,
		low_price: 35,
		big_price: 35,
		sizes: [ 40 ],
		image: Foto,
		number: 1
	}
];
